### ISSUE TITLE
Add Xaero's Fair Play Minimap support

### ISSUE THREAD

**Issue by Dragnier** [ArcaneAlloy/Xaeros-Waystones-Compatibility#1]
The Fair Play Version of Xaero's minimap is not currently working with your mod. The versioning on that one is behind the regular one and your mod requires a higher version than is available as Fair Play.

**Comment by ArcaneAlloy** [comment]
Hmm which what MC version this error is happening?

**Comment by ArcaneAlloy** [comment]
Because we don't have more information. by the moment we close this issue.
