### ISSUE TITLE
Client only?

### ISSUE THREAD

**Issue by pavog** [ArcaneAlloy/Xaeros-Waystones-Compatibility#2]
Hello all,
this is a client-only mod, correct?
Or are there any advantages if I install it on a server aswell?

**Comment by ArcaneAlloy** [comment]
Hi!
No, this is a Client-only mod!

**Comment by ArcaneAlloy** [comment]
We close the issue

**Comment by pavog** [comment]
Okay, thank you!
Maybe you could add a note about this on the project page?
Thank you (again)!

**Comment by ArcaneAlloy** [comment]
Of course!
I already added anote about this in the CurseForge project site

**Comment by Nycto97** [comment]
Just commenting to inform that this mod currently is needed on both client and server (at least for 1.19.2)
